name: AgenticAI Code Quality

on: [push, pull_request]

jobs:
  backend:
    name: Backend Code Quality (Python)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install black ruff

      - name: Check formatting with Black
        run: |
          source .venv/bin/activate
          black --check .

      - name: Lint with Ruff
        run: |
          source .venv/bin/activate
          ruff check .

  frontend:
    name: Frontend Code Quality (React)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install

      - name: Lint with ESLint
        run: |
          npx eslint . --ext .ts,.tsx

      - name: Check formatting with Prettier
        run: |
          npx prettier --check "**/*.{ts,tsx,js,jsx,css,scss,html,json,md}"
